name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    strategy:
      matrix:
        platform: [Net6]
        include:          
          - platform: Net6
            package-name: Net6
            build-dir: net6.0-windows
            proj-name: Smart-de4dot
            solution-name: Smart-de4dot.sln
            config: Release
            dotnet: 6.0.x

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET ${{matrix.dotnet}}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{matrix.dotnet}}

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3   
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
    
    - name: Restore NuGet packages
      run: nuget restore ${{matrix.solution-name}}
      
    - name: Build app for release
      run: msbuild ${{matrix.solution-name}} -t:rebuild -p:Configuration=${{matrix.config}}
      
    - name: Create output directory
      run: New-Item -ItemType Directory -Path C:\builtfiles\${{matrix.proj-name}}-${{matrix.package-name}} -Force > $null
      continue-on-error: true
        
    - name:  Copy release files for upload
      run: Copy-Item -Path T5ive-Tools\bin\Release\${{matrix.build-dir}}\* -Destination C:\builtfiles\${{matrix.proj-name}}-${{matrix.package-name}} -Recurse

    - uses: actions/upload-artifact@v3.1.2        
      with:
        name: ${{matrix.proj-name}} - ${{matrix.build-dir}}
        path: C:\builtfiles\${{matrix.proj-name}}-${{matrix.package-name}}
        if-no-files-found: error
